### PR TITLE
fix data front-end bug #16

### LINKED ISSUE #16: Ensembling fails for atomic models implementing the `reformat`/`selectrows` interface for caching model specific data representations
```julia
using MLJBase, MLJEnsembles, EvoTrees

atom = EvoTreeClassifier()
model = EnsembleModel(atom, n=2)

julia> mach = machine(model, make_moons()...) |> fit!
[ Info: Training Machine{ProbabilisticEnsembleModel{EvoTreeClassifier{Float64,…}},…}.
┌ Error: Problem fitting the machine Machine{ProbabilisticEnsembleModel{EvoTreeClassifier{Float64,…}},…}. 
└ @ MLJBase ~/.julia/packages/MLJBase/hHa7b/src/machines.jl:594
[ Info: Running type checks... 
[ Info: Type checks okay. 
ERROR: type NamedTuple has no field matrix
Stacktrace:
  [1] getproperty(x::NamedTuple{(:x1, :x2), Tuple{Vector{Float64}, Vector{Float64}}}, f::Symbol)                                                                                     
    @ Base ./Base.jl:33
  [2] fit(model::EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}, verbosity::Int64, A::NamedTuple{(:x1, :x2), Tuple{Vector{Float64}, Vector{Float64}}}, y::CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}
)                                                                                          
    @ EvoTrees ~/.julia/dev/EvoTrees/src/MLJ.jl:0
  [3] (::MLJEnsembles.var"#23#27"{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}, Int64, ProgressMeter.Progress, Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}})(train_rows::Vector{Int64})
    @ MLJEnsembles ~/.julia/packages/MLJEnsembles/OsgHR/src/ensembles.jl:163
  [4] iterate
    @ ./generator.jl:47 [inlined]
  [5] collect(itr::Base.Generator{Base.Generator{UnitRange{Int64}, MLJEnsembles.var"#22#26"{Int64, Int64, Random._GLOBAL_RNG}}, MLJEnsembles.var"#23#27"{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}, Int64, ProgressMeter.Progress, Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}}})
    @ Base ./array.jl:681
  [6] map(f::Function, A::Base.Generator{UnitRange{Int64}, MLJEnsembles.var"#22#26"{Int64, Int64, Random._GLOBAL_RNG}})             
    @ Base ./abstractarray.jl:2323
  [7] get_ensemble(::EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}, ::Int64, ::Int64, ::Int64, ::Int64, ::Random._GLOBAL_RNG, ::ProgressMeter.Progress, ::Tables.MatrixTable{Matrix{Float64}}, ::Vararg{Any, N} where N)                                                
    @ MLJEnsembles ~/.julia/packages/MLJEnsembles/OsgHR/src/ensembles.jl:160
  [8] _fit(res::CPU1{Nothing}, func::Function, verbosity::Int64, stuff::Tuple{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}, Int64, Int64, Int64, Random._GLOBAL_RNG, ProgressMeter.Progress, Tuple{Tables.MatrixTable{Matrix{Float64}}, CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}}})
    @ MLJEnsembles ~/.julia/packages/MLJEnsembles/OsgHR/src/ensembles.jl:356
  [9] fit(::MLJEnsembles.ProbabilisticEnsembleModel{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}}, ::Int64, ::Tables.MatrixTable{Matrix{Float64}}, ::CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}})
    @ MLJEnsembles ~/.julia/packages/MLJEnsembles/OsgHR/src/ensembles.jl:444
 [10] fit_only!(mach::Machine{MLJEnsembles.ProbabilisticEnsembleModel{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}}, true}; rows::Nothing, verbosity::Int64, force::Bool)
    @ MLJBase ~/.julia/packages/MLJBase/hHa7b/src/machines.jl:592
 [11] fit_only!
    @ ~/.julia/packages/MLJBase/hHa7b/src/machines.jl:545 [inlined]
 [12] #fit!#56
    @ ~/.julia/packages/MLJBase/hHa7b/src/machines.jl:659 [inlined]
 [13] fit!
    @ ~/.julia/packages/MLJBase/hHa7b/src/machines.jl:657 [inlined]
 [14] |>(x::Machine{MLJEnsembles.ProbabilisticEnsembleModel{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}}, true}, f::typeof(fit!))
    @ Base ./operators.jl:858
 [15] top-level scope
    @ REPL[12]:1
 [16] top-level scope
    @ ~/.julia/packages/CUDA/Axzxe/src/initialization.jl:52

```

Since `EnsembleModel` works directly with the MLJ model interface (and not with machines) this has been overlooked with the introduction of the new  `reformat`/`selectrows` interface.

### PR DESCRIPTION
**Pull request by OkonSamuel**
fixes #16.

```julia
julia> using MLJBase, MLJEnsembles, EvoTrees

julia>

julia> atom = EvoTreeClassifier()
EvoTreeClassifier(
    loss = EvoTrees.Softmax(),
    nrounds = 10,
    λ = 0.0,
    γ = 0.0,
    η = 0.1,
    max_depth = 5,
    min_weight = 1.0,
    rowsample = 1.0,
    colsample = 1.0,
    nbins = 64,
    α = 0.5,
    metric = :mlogloss,
    rng = Random.MersenneTwister(123),
    device = "cpu")

julia> model = EnsembleModel(atom, n=2)
ProbabilisticEnsembleModel(
    model = EvoTreeClassifier(
            loss = EvoTrees.Softmax(),
            nrounds = 10,
            λ = 0.0,
            γ = 0.0,
            η = 0.1,
            max_depth = 5,
            min_weight = 1.0,
            rowsample = 1.0,
            colsample = 1.0,
            nbins = 64,
            α = 0.5,
            metric = :mlogloss,
            rng = Random.MersenneTwister(123),
            device = "cpu"),
    atomic_weights = Float64[],
    bagging_fraction = 0.8,
    rng = Random._GLOBAL_RNG(),
    n = 2,
    acceleration = CPU1{Nothing}(nothing),
    out_of_bag_measure = Any[])

julia> mach = machine(model, make_moons()...) |> fit!
[ Info: Training Machine{ProbabilisticEnsembleModel{EvoTreeClassifier{Float64,…}},…}.

Machine{ProbabilisticEnsembleModel{EvoTreeClassifier{Float64,…}},…} trained 1 time; caches data
  model: MLJEnsembles.ProbabilisticEnsembleModel{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}}
  args:
    1:  Source @538 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @607 ⏎ `AbstractVector{Multiclass{2}}`

```
cc. @ablaom

### CODE REVIEW

File: src/ensembles.jl [hunk 1]
```diff
@@ -21,6 +21,9 @@ function WrappedEnsemble(atom, ensemble::AbstractVector{L}) where L
 end
 
 # to enable trait-based dispatch of predict:
+# The following definitions of `predict` function on `WrappedEnsemble`s, 
+# Xnew` is assumed to be the output of `reformat(atom::Atom, X)` where
+# `X` is the generic representation.
```
Comment (ablaom) [inline src/ensembles.jl]: How about we call this the "user representation" or "external representation".

File: src/ensembles.jl [hunk 2]
```diff
@@ -424,25 +438,26 @@ function MMI.fit(model::EitherEnsembleModel{Atom},
...
+    progress_meter = Progress(
+        n,
+        dt=0.5,
+        desc="Training ensemble: ",
+        barglyphs=BarGlyphs("[=> ]"),
+        barlen=50,
+        color=:yellow
+    )
 
+    stuff = (atom, n, n_patterns, n_train, rng, progress_meter, atom_specific_args)
```
Comment (ablaom) [inline src/ensembles.jl:454]: curious why you pulled `stuff` out of the conditioned block.

**Review by ablaom — APPROVED** [review]
Nice work, thanks!

I'll just push that one tweak to the comment myself.
